#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <friday_night_flippin_icons.h>

int32_t friday_night_flippin_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm friday_night_flippin!");

    return 0;
}
